 <div class="image" style="background-color: #14141f;position: center; text-align: center;"> <img src="img/logo-full.png" style="  margin-left: auto;margin-right: auto; background-color: #14141f;"></div> 
<nav class="navbar navbar-inverse" style="background-color: #14141f;">
     <div class="logo" style="color: white;font-size: 10px;text-align: center;max-width: auto">Golden Lor Yarrabilba- Chinese restaurant shop 7,16-22 Yarrabilba Drive Yarrabilba 4207 <p>By team 03</p></div></p>
  
</div>